// Prueba de punta a punta del configurador en un Chromium real (con WebGL por software).
import http from 'http'; import fs from 'fs'; import path from 'path'; import { execFileSync } from 'child_process'; import { fileURLToPath } from 'url';
import chromium from '@sparticuz/chromium'; import puppeteer from 'puppeteer-core';
const RAIZ = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
execFileSync('python3', ['construir_web.py', '--local'], { cwd: RAIZ });
const MIME = { '.html': 'text/html', '.js': 'text/javascript', '.mjs': 'text/javascript', '.wasm': 'application/wasm', '.json': 'application/json', '.zip': 'application/zip' };
const server = http.createServer((req, res) => {
  const f = path.join(RAIZ, decodeURIComponent(req.url.split('?')[0]));
  fs.readFile(f, (e, d) => { if (e) { res.writeHead(404); res.end('no'); return; } res.writeHead(200, { 'Content-Type': MIME[path.extname(f)] || 'application/octet-stream' }); res.end(d); });
}).listen(8765);
const salida = path.join(RAIZ, 'tests', 'capturas'); fs.mkdirSync(salida, { recursive: true });
let fallos = 0; const chequear = (ok, msg) => { console.log(`${ok ? 'OK   ' : 'FALLA'} ${msg}`); if (!ok) fallos++; };
const browser = await puppeteer.launch({ args: [...chromium.args, '--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'], executablePath: await chromium.executablePath(), headless: 'shell' });
const page = await browser.newPage(); await page.setViewport({ width: 1500, height: 900 });
const consola = []; page.on('console', m => { if (['error', 'warning'].includes(m.type()) && !/GPU stall|swiftshader|ReadPixels/i.test(m.text())) consola.push(m.text()); }); page.on('pageerror', e => consola.push(e.message));
await page.goto('http://localhost:8765/configurador_local.html'); await page.waitForFunction('window.__listo === true', { timeout: 150000 });
const A = (c) => page.evaluate(async (c) => { const r = await window.__app.aplicar(c); return { ok: r.ok, errores: r.errores, avisos: r.avisos, m: r.ok ? r.medidas : null, caja: window.__app.caja(), mallas: window.__app.mallas() }; }, c);
const cerca = (a, b) => Math.abs(a - b) < 0.5;
let r = await page.evaluate(() => ({ ...window.__app.ultimo(), caja: window.__app.caja(), mallas: window.__app.mallas() }));
chequear(r.ok && cerca(r.caja.x, 1880) && cerca(r.caja.y, 2000) && cerca(r.caja.z, 193), `arranque: el 3D mide ${r.caja.x.toFixed(0)} x ${r.caja.y.toFixed(0)} x ${r.caja.z.toFixed(0)} mm (esperado 1880 x 2000 x 193)`);
chequear(r.mallas === r.medidas.n_postes + r.medidas.n_tablas, `arranque: ${r.mallas} piezas dibujadas = ${r.medidas.n_postes} postes + ${r.medidas.n_tablas} tablas`);
await page.screenshot({ path: path.join(salida, '01_inicial.png') });
r = await A({ ancho_total: 2990, alto_total: 1815, profundidad: 300, n_tablas: 27, semilla: 61 });
chequear(r.ok && cerca(r.caja.x, 2990) && cerca(r.caja.y, 1815) && cerca(r.caja.z, 300), 'pedido de 2990 x 1815 x 300 mm: el 3D coincide');
chequear(r.avisos.some(a => a.includes('14 de 27')), 'avisa que solo se ubicaron 14 de 27 tablas');
await page.evaluate(() => window.__app.vista('frontal')); await page.screenshot({ path: path.join(salida, '02_frontal.png') });
await page.evaluate(() => { const x = document.querySelector('#controles input[type=range]'); x.value = 3300; x.dispatchEvent(new Event('input', { bubbles: true })); });
await page.waitForFunction('window.__app.estado().ancho_total === 3300', { timeout: 5000 }); await new Promise(s => setTimeout(s, 1800));
chequear(cerca(await page.evaluate(() => window.__app.caja().x), 3300), 'el slider de ancho (3300 mm) redibuja el mueble');
chequear((await page.evaluate(() => location.hash)).startsWith('#c='), 'la configuración queda guardada en el enlace');
r = await A({ ancho_total: 300 }); chequear(!r.ok && r.errores[0].includes('300'), 'ancho imposible: muestra el error');
r = await A({ ancho_total: 1880, alto_total: 2600 }); chequear(!r.ok && r.errores[0].includes('2420'), 'alto imposible: muestra el error');
r = await A({ ancho_total: 10760, alto_total: 2200, n_tablas: 60, semilla: 3 });
chequear(r.ok && r.m.n_postes === 20 && r.mallas === 20 + r.m.n_tablas && cerca(r.caja.x, 10760), 'caso extremo: 20 postes y 60 tablas');
r = await A({ ancho_total: 1880, alto_total: 2000, profundidad: 193, n_tablas: null, semilla: 0 }); chequear(r.ok, 'vuelve al diseño inicial');
await new Promise(s => setTimeout(s, 1200));
await page.click('#tabs button[data-tab=plan]'); await new Promise(s => setTimeout(s, 700)); await page.screenshot({ path: path.join(salida, '03_plan.png') });
chequear(await page.evaluate(() => !!document.querySelector('#plan-contenido svg') && /placas/.test(document.querySelector('#plan-contenido').innerText)), 'pestaña Plan de corte: muestra el SVG y las placas');
await page.click('#tabs button[data-tab=datos]'); await new Promise(s => setTimeout(s, 300));
chequear(await page.evaluate(() => /Escuadra en U/.test(document.querySelector('#datos-contenido').innerText)), 'pestaña Datos técnicos: incluye la escuadra en U');
chequear(consola.length === 0, 'sin errores ni avisos en la consola del navegador' + (consola.length ? ': ' + consola.slice(0, 3).join(' | ') : ''));
await browser.close(); server.close();
if (fallos) { console.error(`\n${fallos} prueba(s) fallaron`); process.exit(1); } console.log('\nTodas las pruebas pasaron.');
